[tool.poetry]
name = "essencia.deta"
version = "0.1.3"
description = "Deta base for essencia enterprise."
authors = ["arantesdv <arantesdv@me.com>"]
license = "MIT"
packages = [
    { include = "essencia" },
]

[tool.poetry.dependencies]
python = "^3.7"
deta = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
