[tool.poetry]
name = "api-project-generator"
version = "0.6.0"
description = ""
authors = ["Gustavo Correa <self.gustavocorrea@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
api-project = "api_project_generator.main:app"

[tool.poetry.dependencies]
python = "^3.9"
GitPython = "^3.1.18"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
pylint = "^2.9.6"
typing-extensions = "^3.10.0"

[tool.isort]
profile = "black"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.6.0"
tag_format = "$version"
version_files = ["api_project_generator/__init__.py"]
update_changelog_on_bump = true


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
